### ISSUE TITLE
.travis build failures dues to limitation in docker container

### ISSUE THREAD

**Issue by shroffk** [epics-base/pvAccessJava#12]
ChannelAccessIFRemoteTest are currently failing on travis while still succeeding on Jenkins. The most likely reason is that the docker container has limitation on the n/w configuration which results in some of the client unit test failing to connect to the server (https://travis-ci.org/epics-base/pvAccessJava/builds/274601801?utm_source=github_status&utm_medium=notification)

@mdavidsaver @mrkraimer @ralphlange 
During the epics meeting it was stated that these tests should be considered as bad tests which should be updated.

**Comment by mdavidsaver** [comment]
Try EPICS_PVA_ADDR_LIST=127.255.255.255
