### ISSUE TITLE
Tests are not running well on machine with multiple networks

### ISSUE THREAD

**Issue by ralphlange** [epics-base/pvAccessJava#3]
When running the tests on a machine with multiple network interfaces, they produce a lot of warnings:
```
[warning] More than one channel with name 'valueOnly' detected, connected to: /127.0.0.1:5075, ignored: /192.168.56.1:5075
[warning] More than one channel with name 'valueOnly' detected, connected to: /127.0.0.1:5075, ignored: /10.14.32.46:5075
```
While this is not failing the tests, it would probably be better to run them with explicit network configuration, preferably on localhost to avoid external side effects.

**Comment by ralphlange** [comment]
Ping ... issue still exists. (Still annoying.)

**Comment by msekoranja** [comment]
Pong... I know, this issue hangs over me.

**Comment by ralphlange** [comment]
Damokles!
