### ISSUE TITLE
Manifest instruction was reverted

### ISSUE THREAD

**Issue by berryma4** [epics-base/pvAccessJava#8]
This instruction seems to be reverted:
https://github.com/epics-base/pvAccessJava/commit/07bf4ee6bb52b58cb5ba7d175b59d2f6828e4f18

**Comment by anjohnson** [comment]
As with your pvDataJava issue, you seem to be expecting versions that are on an old release branch. Work on pvAccessJava is currently on the release/5.0 branch.

**Comment by ralphlange** [comment]
Added to branches release/4.1, release/5.0 and master

**Comment by berryma4** [comment]
Thank you so much!!!!
